<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>Playlist</h2>
    <form action="/spotify/addtoplaylist" method="POST">
        <label for="playlist">Choose a playlist:</label>
 
        <select name="playlist" id="playlist">
            <option value="0">Choose Playlist</option>
            <?php foreach ($playlist['items'] as $k => $v) {
                $html .= '<option value=' . $v['id'] . '>' . $v['name'] . '</option>';
            }
            echo $html;
            ?>
        </select>
        <br>
        <input type="submit" name="addtoplaylist" value="Add Song" class="btn btn-success">
    </form>
</body>

</html>